# Generated by Django 3.2.9 on 2022-06-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField(default='M')),
                ('address', models.TextField(default='India')),
                ('age', models.TextField()),
                ('salary', models.TextField()),
            ],
        ),
    ]
